# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

    steps:
      - checkout
      - run:
        name: install dependencies
        command: |
        python3 -m venv venv
        - venc/bin/active
        pip install -r requirements.txt
#3 Run coding convention soft and the tester 
  - run:
    name: run tests
    command: |
    - venc/bin/active
    flake8 --exclude-env* --statistics
    pytest --junixml-test-results/junit.xml
  - store_test_results:
      path: test-results
      
  - store_artifacts:
    path: test-results