# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
    - image: circleci/python:3.7

  working_directory: ~/UCModule5
  
  steps:
    #1 Obtain repo from Github
    - checkout
#2 Create a virtual enviroment and install dependencies
    -run:
      name: install dependencies
      command: |
      python3 -m venv venv
      - venc/bin/active
      pip install -r requirements.txt
    
    #3 Run coding convention software plus tester.
    -run:
      name: run tests
      command: |
      - venc/bin/active
      flake8 --exclude-env* --statistics
      pytest --junixml-test-results/junit.xml
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: test-results