version: 2
jobs:
  build:
    docker:
      - image: circleci/python3.7
  working_directory: ~/UCModule5

  steps:
    - checkout
    - run:
        name: install dependencies 
        command: |
          python3 -m venv venv
          . venv/bin/active
          pip install -r requirements.txt
    - run:
        name: run tests
        command: |
          . venv/bin/active
          flake8 --exclude-env* --statistics
          pytest --junixml-test-results/junit.xml
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: test-results